pub const HEIGHT_SPRITES: f32 = 73.;
pub const PADDING_VERTICAL: f32 = 17.5;
pub const HEIGHT_BLOCK: f32 = HEIGHT_SPRITES + PADDING_VERTICAL * 2.;
pub const NUMBER_OF_VERTICAL_BLOCKS: f32 = 1080. / HEIGHT_BLOCK;

pub const WIDTH_SPRITES: f32 = 100.;
pub const PADDING_HORIZONTAL: f32 = 30.;
pub const WIDTH_BLOCK: f32 = WIDTH_SPRITES + PADDING_HORIZONTAL * 2.;
pub const NUMBER_OF_HORIZONTAL_BLOCKS: f32 = 1920. / WIDTH_BLOCK;
